# config/packages/api_platform.yaml

api_platform:
    title: Hello API Platform
    version: 1.0.0

    # ------ Ajoute ce bloc ------
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Dto'
    # ----------------------------

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
