nelmio_cors:
    defaults:
        allow_origin: ['*'] # en prod, remplace * par ton frontend Vercel
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['https://matchroom-git-dev-samidehils-projects.vercel.app']
